### ISSUE TITLE
Add endpoint to register summary stats metadata for download and validation

### ISSUE THREAD

**Issue by tudorgroza** [EBISPOT/gwas-sumstats-service#1]
* Proposed endpoint: `POST /v1/sum-stats`
 * Proposed payload:

```
	{
	  "requestEntries": [
	    {
	      "id": "mKoYvoLH8L",			// (M) ID provided by the backend
	      "filePath": "3iMfjk5tT8",		// (M) File path as provided in the template
	      "md5": "uWhQu0BU1X",			// (M) MD5 as provided in the template
	      "assembly": "hmIWgAjeHP"		// (O) Assemble as provided in the template
	    },
	    {
	      "id": "QaPsZpzN7k",
	      "filePath": "rSqACQgoPA",
	      "md5": "Wl0GUyX0Hd",
	      "assembly": "9ybzqm63Sj"
	    }
	  ]
	}
```
 * Proposed response: `String`
   * The `String` response should represent a callback ID the backend can use to poll the endpoint described here: https://github.com/EBISPOT/gwas-sumstats-service/issues/2 to retrieve the status updates.

 * Note:
   * (M) - denotes `Mandatory` | (O) - denotes `Optional`

**Comment by jdhayhurst** [comment]
Looks good. Can we make the assembly mandatory though i.e. all fields here are mandatory.
