### ISSUE TITLE
Add endpoint to retrieve validation status updates based on callback ID

### ISSUE THREAD

**Issue by tudorgroza** [EBISPOT/gwas-sumstats-service#2]
* Proposed endpoint: `GET /v1/sum-stats/{callbackId}`
 * Proposed response:
```
	{
	  "callbackId": "Hvi44",		// (M)
	  "completed": false,			// (M) Flag to denote completion of the batch
	  "statusList": [
	    {
	      "id": "V2JgyZuomg",		// (M) ID provided in the registration call for this entry
	      "status": "rBPnqPL2KU",	// (M) Current status
	      "error": "L3NiavbfgQ"		// (O) Error message if status is not successful
	    },
	    {
	      "id": "2AMf4WB40Y",
	      "status": "vMwxBSipr0",
	      "error": "4PVehwPTvV"
	    }
	  ]
	}
```
 * Note:
   * (M) - denotes `Mandatory` | (O) - denotes `Optional`
   * `callbackId` is the response provided by this service when registering a validation request per: https://github.com/EBISPOT/gwas-sumstats-service/issues/1
   * `completed` should be set to `TRUE` when the entire batch has been finalised - independently on the type of outcome
   * `id` in each entry above should correspond to the IDs provided by the request - as per https://github.com/EBISPOT/gwas-sumstats-service/issues/1

**Comment by jdhayhurst** [comment]
That all looks good. The status will either be:
`valid`, `validating` or `invalid`. 
So they'll only be errors if the status is `invalid`.
