### ISSUE TITLE
Fix globus cleanup authentication issue 

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-sumstats-service#252]
the authentication on the transfer client, when performing the post validation cleanup is failing. 

- [x] Test in sandbox

**Comment by ljwh2** [comment]
From James: Hi both, I followed up on the celery error “Celery error in sumstats_service.app.publish_and_clean_sumstats”. At first I thought we didn’t deploy the changes that Sajo and Ala made but those are in released in production. I tried to replicate the issue by running the remove_endpoint_and_all_contents() method directly from one of the pods running in the prod cluster with the globus folder in the email d8dad4a0-f099-4706-b016-f302e2b90ab9 and I could not replicate the error i.e. it worked, no issues at all. All I can think of is that maybe there’s an issue with the oauth token flow, I wonder if ashutosh has maybe faced this. The point in the code where it’s failing is here, but as I said, when I run this, it works.

**Comment by ljwh2** [comment]
Check how close we are to 1000 limit. Clean up manually if necessary, then defer for new starter. @sajo-ebi

**Comment by karatugo** [comment]
For local development, I worked on the Docker setup. Please find the pull request here. https://github.com/EBISPOT/gwas-sumstats-service/pull/271

**Comment by karatugo** [comment]
Updated Celery environment variables files with the correct Globus variables.

**Comment by karatugo** [comment]
Tested in sandbox and added `GLOBUS_HOSTNAME` as well.

**Comment by karatugo** [comment]
Test OK. Nothing to merge to dev or master because the changes were only in env var files.

**Comment by karatugo** [comment]
Can be closed.
