### ISSUE TITLE
Update Sumstats service Confluence Documentation

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-sumstats-service#357]
The GWAS Sumstats Service documentation in confluence [here](https://www.ebi.ac.uk/seqdb/confluence/pages/viewpage.action?spaceKey=GOCI&title=Summary+Statistics+Service) is outdated

All the cluster commands needs to changed from the previous bsub commands (LSF) to sbatch (Slurm)

**Comment by karatugo** [comment]
Updated the Confluence docs.

**Comment by karatugo** [comment]
Note that the troubleshooting section is old. Besides I don't recall any occasion where I needed something from that section. But anyway it might be useful, so I'm not deleting it. Updated LSF sections there too.
