### ISSUE TITLE
globus integration

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-sumstats-service#36]
Merge in [globus app](https://github.com/EBISPOT/ftp-service/blob/master/rest_ftp/globus.py) so that it runs in the same flask app as the sumstats service. 

### Enable creation of globus endpoints
Make a POST request to `/v1/sum-stats/globus/mkdir` with a json payload like the following example:

`{"unique_id": "6D3DC906-2370-4E17-BF91-8A08A26E3E4F", "email": <email address>}` 

This will create the directory on the private ftp server with the 'unique_id' as the directory name, returning 201 if the directory is successfully built or already exists. It will also send a message to the provided email address, which should belong to the data submitter.

### Sumstats service change
When making a POST request to the sumstats service, an additional field should be supplied:
```
{
	"requestEntries": [{
		"id": "abc123",
		"filePath": "sumstats_file.tsv",
		"md5": "a1195761f082f8cbc2f5a560743077cc",
		"assembly": "GRCh38",
		"readme": "optional text",
		"entryUUID": "6D3DC906-2370-4E17-BF91-8A08A26E3E4F"
	}]
}
```

**Comment by tudorgroza** [comment]
@jdhayhurst - will work on this today.
