### ISSUE TITLE
Return Globus endpoint ID from mkdir command

### ISSUE THREAD

**Issue by jstewart-ebi** [EBISPOT/gwas-sumstats-service#42]
When creating a new folder with Globus, system needs to return the new endpoint ID to the deposition system in order to create the URL for the user to open their folder.

Globus mkdir command needs to return: submission ID, endpoint ID, and status.

**Comment by jdhayhurst** [comment]
Make a POST request to `/v1/sum-stats/globus/mkdir` with a json payload like the following example:

`{"submission_id": "6D3DC906-2370-4E17-BF91-8A08A26E3E4F", "email": <email address>}` 

Response:
```
{"status": "ok",
 "submission_id": "6D3DC906-2370-4E17-BF91-8A08A26E3E4F", 
 "endpoint_id": "02ECDC69-32E2-4217-A949-37AB1AF4A4A9"}
```

This will create the directory on the private ftp server with the 'submission_id' as the directory name, returning 201 if the directory is successfully built or already exists. Globus directories come with 'endpoint IDs' which enable users to access the directory. This endpoint ID will be returned. 

### Sumstats service change
When making a POST request to the sumstats service, an additional field should be supplied:
```
{
	"requestEntries": [{
		"id": "abc123",
		"filePath": "sumstats_file.tsv",
		"md5": "a1195761f082f8cbc2f5a560743077cc",
		"assembly": "GRCh38",
		"readme": "optional text",
		"submission_id": "6D3DC906-2370-4E17-BF91-8A08A26E3E4F"
	}]
}
```

**Comment by jdhayhurst** [comment]
change `endpoint_id` to `globusOriginID` and for consistency, change `unique_id` to `uniqueID` in all instances
