### ISSUE TITLE
resolve timeout issue for large submissions by making POST to register sumstats an asynchronous task

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-sumstats-service#96]
A POST with a large number of studies can cause a timeout due to the payload validation and storing in mongo before returning the callback id. 
Proposed change: 
1. return the callback id immediately with 201 - the callback can be polled immediately with GET requests as usual
2. async validate payload metadata - status will be RETRIEVING
Then as usual async validate the files.

@tudorgroza comment if anything sounds off there

**Comment by jdhayhurst** [comment]
```
Request: 
POST to /v1/sum-stats/

Response: 201 
{"callbackID": "cbmKLJYf"}

-------------------------------------
Request: 
GET to /v1/sum-stats/cbmKLJYf

Response: 200
{"callbackID": "cbmKLJYf", "status": "PROCESSING"}

when async processing of metadata has finished:
if metadata not ok:
{"callbackID": "cbmKLJYf", "status": "INVALID", "metadataErrors": [<list of errors>]}

else metadata ok (unchanged scenario):
- data not ok:
  {'callbackID': 'cbmKLJYf', 'completed': True, 'statusList': [{'id': 'abc123', 'status': 'INVALID', 'error': '<error description>', 'gcst': None}]} 
- data ok:
  {'callbackID': 'cbmKLJYf', 'completed': True, 'statusList': [{'id': 'abc123', 'status': 'VALID', 'gcst': None}]} 

```

**Comment by tudorgroza** [comment]
@jdhayhurst - the changes above will break my calls for various reasons:
 * I'm expecting `completed` and `statusList` to always be there, populated and non-empty
 * my deserialization method cannot cater - as it stands - for unknown fields like `status` and `metadataErrors`

Let us fix them together :)
 * I will make `statusList` optional
 * please add `completed` - `T|F` in all responses
 * please add `status` in all responses

So:
 * This:
```
{"callbackID": "cbmKLJYf", "status": "PROCESSING"}
```
should be:
```
{"callbackID": "cbmKLJYf", "status": "PROCESSING", "completed": false}
```

* This:
```
{"callbackID": "cbmKLJYf", "status": "INVALID", "metadataErrors": [<list of errors>]}
```
should be:
```
{"callbackID": "cbmKLJYf", "status": "INVALID", "completed": true, "metadataErrors": [<list of errors>]}
```

* This (and the other data response):
```
{'callbackID': 'cbmKLJYf', 'completed': True, "status": "DONE", 'statusList':  ....}
```
should be:
```
{'callbackID': 'cbmKLJYf', 'completed': True, "status": "DONE", 'statusList':  ....}
```

For this last one - please choose whatever `status` value you want (I've used `DONE` just as an example) and let me know what you chose. Thank you.

**Comment by jdhayhurst** [comment]
Looks good I'll update and let you know

**Comment by tudorgroza** [comment]
Thank you!

**Comment by jdhayhurst** [comment]
@tudorgroza Updated to comply with your suggestion, so `status` and `completed` are always present. For the `status` field, the value will be as follows:
```
'PROCESSING' if any study status is 'RETRIEVING'
'INVALID' if any study status is 'INVALID' or metadata errors
'VALID' if any study status is 'VALID'
```
`status` is the overall status of the payload
`complete` is then redundant as it can be inferred - it will be `true` if status is `INVALID|VALID` and `false` if `PROCESSING`, but we can leave it in if it helps.

**Comment by tudorgroza** [comment]
@jdhayhurst - thank you.
One last check - `metadataErrors` is a list of `String` - correct?

**Comment by tudorgroza** [comment]
Changed done and deployed in Sandbox on my side as well.

**Comment by jdhayhurst** [comment]
1) Yes, `metadataErrors` is a list of `String`
2) OK I'll go ahead and remove the `complete` flag.
